### ISSUE TITLE
dodanie argumentu ktory ma dwie częsci 

### ISSUE THREAD

**Issue by robalmeister** [Rollczi/LiteCommands#129]
Chodzi mi tu ze chce zgetowac swoj clan za pomoca playera ale nie wiem jak to zrobic i nie chce zeby bylo w executcie tylko w argumentach

**Comment by Osnixer** [comment]
Iterujesz clany i sprawdzasz w którym jest dany gracz, potem tworzysz sobie argument który zwraca ci ten clan.

**Comment by robalmeister** [comment]
a taki przykladowy kod?

**Comment by Rollczi** [comment]
@robalmeister https://github.com/Rollczi/LiteCommands/blob/master/examples/bukkit/src/main/java/dev/rollczi/example/bukkit/argument/WorldArgument.java

**Comment by niemiecki999** [comment]
@deestt podaj discorda
