### ISSUE TITLE
naprawić inne statyczne clasy w classie

### ISSUE THREAD

**Issue by robalmeister** [Rollczi/LiteCommands#136]
chodzi mi tu że jak robiłem gamemode to chciałem gm1 gm2 i itd. to gdy zrobilem staticzna classe to tabowalo w /gamemode 1/2 i gm1/gm2

**Comment by Rollczi** [comment]
podaj przykładowy kod takiej komendy

**Comment by robalmeister** [comment]
`import dev.rollczi.litecommands.argument.Arg;
import dev.rollczi.litecommands.argument.Name;
import dev.rollczi.litecommands.command.execute.Execute;
import dev.rollczi.litecommands.command.section.Section;
import org.bukkit.GameMode;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

@Section(route = "gamemode", aliases = {"gm", "gamem"})
//na testa walilem wiec nie patrz ze nie ma annotation
public class GameModeCommand {
    @Execute(min = 1, max =1)
    public void gameMode(Player sender, @Arg @Name("gamemode") GameMode gameMode) {
        sender.setGameMode(gameMode);
        sender.sendMessage("Ustawiono tryb na "+ gameMode.name() + "!");
    }
    @Execute(min = 2)
    public void gameModeToPlayer(CommandSender sender, @Arg @Name("gamemode") GameMode gameMode, @Arg @Name("gracz") Player target) {
        target.setGameMode(gameMode);
        sender.sendMessage("Ustawiono graczowi " + target.getName() + " tryb na " + gameMode.name() + "!");
    }
    //zrobie jedna bo mi sie nie chce
    @Section(route = "gamemode1", aliases = {"gm1", "gmc", "creative", "gmcreative", "gamemodecreative"})
    public static class Creative {
        @Execute(max = 0)
        public void gameModeCreative(Player sender) {
            GameMode gameMode = GameMode.CREATIVE;
            sender.setGameMode(gameMode);
            sender.sendMessage("Ustawiono tryb na "+ gameMode.name() + "!");
        }
        @Execute(min = 1)
        public void gameModeCreativeToPlayer(Player sender, @Arg @Name("gracz") Player target) {
            GameMode gameMode = GameMode.CREATIVE;
            target.setGameMode(gameMode);
            sender.sendMessage("Ustawiono graczowi " + target.getName() + " tryb na " + gameMode.name() + "!");
        }
    }
}`

**Comment by robalmeister** [comment]
```
import dev.rollczi.litecommands.LiteCommands;
import dev.rollczi.litecommands.bukkit.adventure.paper.LitePaperAdventureFactory;
import dev.rollczi.litecommands.bukkit.tools.BukkitPlayerArgument;
import net.onlybis.rollczitest.gamemode.GameModeArgument;
import net.onlybis.rollczitest.gamemode.GameModeCommand;
import org.bukkit.GameMode;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

public final class RollcziTest extends JavaPlugin {
    private LiteCommands<CommandSender> liteCommands;
    @Override
    public void onEnable() {
       liteCommands = LitePaperAdventureFactory
               .builder(this.getServer(), "test")
               .argument(Player.class, new BukkitPlayerArgument<>(getServer(), "test"))
               .argument(GameMode.class, new GameModeArgument())
               .command(GameModeCommand.class, GameModeCommand.Creative.class)
               .register();

    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}
```

**Comment by robalmeister** [comment]
![obraz](https://user-images.githubusercontent.com/65306693/192460491-b88673fb-382c-46f4-88d8-89c3a7a28e39.png)

**Comment by robalmeister** [comment]
zapomnialem dodac contexualbind ale jest dodany

**Comment by Rollczi** [comment]
Wszystko tabuje poprawnie tak jak zrobiłeś.
czyli
- `@Arg @Name("gamemode") GameMode gameMode` (/gamemode \<gamemode> [player]) (lista z GameModeArgument)
- `@Section(route = "gamemode1", aliases = {"gm1", "gmc", "creative", "gmcreative", "gamemodecreative"})` (/gamemode creative [player]) (rzeczy z route i aliases)

Powinieneś zrobić wszystko w `GameModeArgument`.

Jest kolizja po wpisaniu np. `/gamemode creative` bo nie wiadomo czy wykonać komendy z 
`@Arg @Name("gamemode") GameMode gameMode`
czy z 
`@Section(route = "gamemode1", aliases = {"gm1", "gmc", "creative", "gmcreative", "gamemodecreative"})` + `@Execute(max = 0)`
