### ISSUE TITLE
BungeeCord strange no-permission message

### ISSUE THREAD

**Issue by BlackBaroness** [Rollczi/LiteCommands#207]
When I declare permission via annotation at BungeeCord and the player tries to execute this command without permission, he just receives permission as a message. I mean in raw format, just "permissionYouTyped".

**Comment by Osnixer** [comment]
> When I declare permission via annotation at BungeeCord and the player tries to execute this command without permission, he just receives permission as a message. I mean in raw format, just "permissionYouTyped".

You need to create permission handler and return a message what you want.

Example on bukkit equals as bungee: []()

**Comment by BlackBaroness** [comment]
I am sorry, I forgot about that. Thank you.
