### ISSUE TITLE
Add exception handling to async commands

### ISSUE THREAD

**Issue by BlackBaroness** [Rollczi/LiteCommands#213]
Hi, I have noticed that `@Async` commands does not print stack trace. Yes, we can work out it by using CompletableFuture, but this will look bad. What about adding some kind of exception handling for commands like this? For me, just printing stackstace would be enough.

**Comment by Rollczi** [comment]
Good idea, I think exception can be handled in [ExecuteResultHandler.java](https://github.com/Rollczi/LiteCommands/blob/master/litecommands-core/src/main/java/dev/rollczi/litecommands/handle/ExecuteResultHandler.java).

**Comment by Rollczi** [comment]
Available on version `2.8.8-SNAPSHOT` in snapshot repositories:
- `https://repository.minecodes.pl/snapshots`
- `https://repo.eternalcode.pl/snapshots`
