### ISSUE TITLE
Add Enum argument resolver

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#221]
### Helpful informations:
Package with basic arguments.
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/5c3e21a4-a671-4e2c-8716-78651fb09d79)
Register argument:
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/864bc531-50d7-4923-9e1c-d562e991a508)

**Comment by BlackBaroness** [comment]
Assign this to me, please. I will do it

**Comment by Rollczi** [comment]
Okey, I assigned you to issue

![Image](https://github.com/Rollczi/LiteCommands/assets/49173834/1e548d60-316c-4642-ba51-0f51c29f1b54)

I created Github Project for LiteCommands, you can check if you can read the table. https://github.com/users/Rollczi/projects/2/views/2 Does this look good to you?

**Comment by BlackBaroness** [comment]
> I created Github Project for LiteCommands, you can check if you can read the table. https://github.com/users/Rollczi/projects/2/views/2 Does this look good to you?

Yep, it's good

**Comment by BlackBaroness** [comment]
Hey, @Rollczi, in 2.x version it was very easy to support such case, but here it seems really difficult. Currently, we don't have any typed argument example (flag and others don't have generics)

I see we can access target argument class by using `WrapFormat`, but we need to do some argument magic first. Splitting logic to `EnumArgument` and `EnumArgumentResolver` and creating that argument by `ArgArgumentProcessor` seems like something that must work, but I am not sure if it's a true solution. Also, it requires a lot of unchecked casts
