### ISSUE TITLE
Add Duration/Period etc... argument resolvers

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#222]
### Helpful informations:
Duration parser: https://github.com/Rollczi/LiteCommands/blob/master/litecommands-core/src/dev/rollczi/litecommands/time/DurationParser.java
Package with basic arguments.
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/5c3e21a4-a671-4e2c-8716-78651fb09d79)
Register argument:
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/864bc531-50d7-4923-9e1c-d562e991a508)

**Comment by BlackBaroness** [comment]
What about using `https://github.com/BlackBaroness/duration-serializer-java/`? I am ready to add more formats if necessary. I just would more flexible
I am going to implement this

**Comment by BlackBaroness** [comment]
Okay then. Assign this to me if possible please, I will do this in a couple of days

**Comment by Rollczi** [comment]
> Okay then. Assign this to me if possible please, I will do this in a couple of days

One PR is already created https://github.com/Rollczi/LiteCommands/pull/227 (only for Duration)
But still no for Period or other time units like Instant, LocalTime etc...

**Comment by Rollczi** [comment]
> Assuming how `Period` creation works, I don't see real difference between `Duration` and `Period` parsers

`Duration` - short units as seconds, minutes, hours, days etc.
`Period` - long units as days, weeks, months, years etc.

`1 month` in `Period` depending on the current time context it may represent after conversion to `Duration` e.g `28 days` `30 days` or `31 days`


> Also, [https://docs.rollczi.dev/documentation/litecommands/features/argument-time-types.html](this) documentation part says that LiteCommands already has mentioned types support

Documentation is not updated yet :/
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/8866b4a6-f475-4b0b-a047-02f3c9754322)

**Comment by CitralFlo** [comment]
Hello! I will finish this with `Period` Argument support.
Sorry for taking issue from You BlackBaroness

**Comment by Rollczi** [comment]
TODO Period
