### ISSUE TITLE
Better error printing when annotations @Context or @Arg are missing.

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#224]
See [PrettyPrint](https://github.com/Rollczi/LiteCommands/blob/master/litecommands-core/src/dev/rollczi/litecommands/prettyprint/PrettyPrint.java)

**Comment by Akshayp02** [comment]
hey i would like to work on this issue can you assign me with some description.

**Comment by Rollczi** [comment]
Hey, no problem. 
When you forget to add the `@Arg` or `@Context` annotation, there is no clear notification at the start of LiteCommands that the annotation is missing. 
I think this should be handled at this place:
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/c75048b5-ef67-4c62-83c0-e7b948e06db3)

**Comment by Rollczi** [comment]
@Akshayp02 Are you still working on this issue?
