### ISSUE TITLE
Add Instatnt argument resolver support

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#233]
### Helpful information:
Package with basic arguments.
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/5c3e21a4-a671-4e2c-8716-78651fb09d79)
Register argument:
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/864bc531-50d7-4923-9e1c-d562e991a508)

**Comment by BlackBaroness** [comment]
Please assign this to me @Rollczi

**Comment by Rollczi** [comment]
> Please assign this to me @Rollczi

Done
