### ISSUE TITLE
Add BigInteger and BigDecimal argument support

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#236]
### Helpful information:
Package with basic arguments.
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/5c3e21a4-a671-4e2c-8716-78651fb09d79)
Register argument:
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/864bc531-50d7-4923-9e1c-d562e991a508)

**Comment by BlackBaroness** [comment]
@Rollczi, I will do it

**Comment by Rollczi** [comment]
Okay, I assigned you
