### ISSUE TITLE
Update the plugin to the latest build. And updated for LiteCommands 3.x

### ISSUE THREAD

**Issue by Jakubk15** [Rollczi/LiteCommands#238]
I'm currently on the latest build of IntelliJ IDEA Ultimate, and the plugin refuses to load. The plugin requires bump to build 232.x.
![image](https://github.com/Rollczi/LiteCommands/assets/77227023/7ec9879f-fa59-46ee-a381-3fcb523af937)
![image](https://github.com/Rollczi/LiteCommands/assets/77227023/5970cb7e-188e-444b-95da-990b03c0b90f)

**Comment by Rollczi** [comment]
Related https://github.com/LiteDevelopers/LiteCommands-IntelliJPlugin

**Comment by Jakubk15** [comment]
> Related https://github.com/LiteDevelopers/LiteCommands-IntelliJPlugin

I literally thought I created this issue on the plugin repository, thanks

**Comment by Rollczi** [comment]
https://github.com/LiteDevelopers/LiteCommands-IntelliJPlugin/pull/3
