### ISSUE TITLE
Considering support `@OptionalArg` to mark a Optional argument instead of using `Optional<?>`.

### ISSUE THREAD

**Issue by CarmJos** [Rollczi/LiteCommands#305]
Using `org.jetbrains.annotations.Nullable` instead of using `Optinal<?>` in function's arguments will avoid many issues while also complying with general Java development specifications.

Otherwise, `@SuppressWarnings("OptionalUsedAsFieldOrParameterType")` is always needed, and will still influence code factors' score.

**Comment by Rollczi** [comment]
@CarmJos, org.jetbrains.annotations.Nullable is annotated RetentionPolicy to CLASS
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/f0eb8cf7-7f44-4f4f-81b4-aac7a7d92f88)

**Comment by CarmJos** [comment]
How about  [@checkerframework.checker.nullness.qual.Nullable](https://checkerframework.org/api/org/checkerframework/checker/nullness/qual/Nullable.html) ?

**Comment by CarmJos** [comment]
Or just provide a "@NullableArg"?

**Comment by Rollczi** [comment]
hmmm, 
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/9cc95bf8-e623-48fc-ad4f-837e4f54d9f1)
@NullableArg seems to be a bit longer than the other arguments. I think your first concept is better.

**Comment by Rollczi** [comment]
There is also an option to add attribute @Arg(nullable = true)

**Comment by CarmJos** [comment]
Well, that's great enough. Thanks a lot!

**Comment by CarmJos** [comment]
> hmmm, 
> ![image](https://github.com/Rollczi/LiteCommands/assets/49173834/9cc95bf8-e623-48fc-ad4f-837e4f54d9f1)
> @NullableArg seems to be a bit longer than the other arguments. I think your first concept is better, but also I don't want to take the `Nullable` (this will interfere with the use of jetbrains annotations)

In my opinion，This annotation is Male longer than others but It can describe the argument more clearly. Also, We entered the single `@NullableArg` annotation will better than add the `nullable = true` in `@Arg` annotation due to shorter length and ide support.

**Comment by Rollczi** [comment]
> > hmmm,
> > ![image](https://private-user-images.githubusercontent.com/49173834/285692311-9cc95bf8-e623-48fc-ad4f-837e4f54d9f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODA5MDcsIm5iZiI6MTcwMTA4MDYwNywicGF0aCI6Ii80OTE3MzgzNC8yODU2OTIzMTEtOWNjOTViZjgtZTYyMy00OGZjLWFkNGYtODM3ZTRmNTRkOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDEwMjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTI3NGYzNzliNTM4NDdmNGNkMTIzOGMyNTI0NDU3Y2RiNGYzNTBmODQ2MDkwNzYyZjdlMDdmMWI2ZTA0NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_0Bxq01Op6g3y1W4Ut8OdS0Uf2LNlIFicTx7sUlvDs)
> > @NullableArg seems to be a bit longer than the other arguments. I think your first concept is better, but also I don't want to take the `Nullable` (this will interfere with the use of jetbrains annotations)
> 
> In my opinion，This annotation may longer than others but it can describe the argument more clearly. Also, We entered the single `@NullableArg` annotation will better than add the `nullable = true` in `@Arg` annotation due to shorter length and ide support.

I asked LiteCommands community about this feature on [discord](https://discord.com/invite/6cUhkj6uZJ) 
Also, you can vote for it -> [pull](https://strawpoll.com/GJn47Vb68yz)

I got another way (from @P3ridot) that would be more consistent with the current API:
`@Arg(optional = true)`

**Comment by CarmJos** [comment]
> > > hmmm,
> > > ![image](https://private-user-images.githubusercontent.com/49173834/285692311-9cc95bf8-e623-48fc-ad4f-837e4f54d9f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODA5MDcsIm5iZiI6MTcwMTA4MDYwNywicGF0aCI6Ii80OTE3MzgzNC8yODU2OTIzMTEtOWNjOTViZjgtZTYyMy00OGZjLWFkNGYtODM3ZTRmNTRkOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDEwMjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTI3NGYzNzliNTM4NDdmNGNkMTIzOGMyNTI0NDU3Y2RiNGYzNTBmODQ2MDkwNzYyZjdlMDdmMWI2ZTA0NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_0Bxq01Op6g3y1W4Ut8OdS0Uf2LNlIFicTx7sUlvDs)
> > > @NullableArg seems to be a bit longer than the other arguments. I think your first concept is better, but also I don't want to take the `Nullable` (this will interfere with the use of jetbrains annotations)
> > 
> > In my opinion，This annotation may longer than others but it can describe the argument more clearly. Also, We entered the single `@NullableArg` annotation will better than add the `nullable = true` in `@Arg` annotation due to shorter length and ide support.
> 
> I asked LiteCommands community about this feature on [discord](https://discord.com/invite/6cUhkj6uZJ) 
> Also, you can vote for it -> [pull](https://strawpoll.com/GJn47Vb68yz)
> 
> I got another way (from @P3ridot) that would be more consistent with the current API:
> `@Arg(optional = true)`
> 

 Followed by this, Maybe we can support a new annotation called '@OptionalArg'.

**Comment by CarmJos** [comment]
Another main reason why I personally do not recommend adding new parameters to `@Arg` is that when I also need to set a name for the optional argument, the entire annotation will become very long, which looks like this:

```
@Arg(value = "target",nullable = true) Player player
```

If using the `@OptionalArg`, it will look like this:

```
@OptionalArg("target") Player player
```

**Comment by Rollczi** [comment]
> Another main reason why I personally do not recommend adding new parameters to `@Arg` is that when I also need to set a name for the optional argument, the entire annotation will become very long, which looks like this:
> 
> ```
> @Arg(value = "target",nullable = true) Player player
> ```
> 

Yeah, you are right. 
Poll don't clearly show a better solution to do this, but I think your `@NullableArg` seems to be the best way in this situation.
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/047d5bad-cc5c-47de-90b1-34a5972641fb)

So, I will implement `@NullableArg`. Thanks for your help!

**Comment by CarmJos** [comment]
> > Another main reason why I personally do not recommend adding new parameters to `@Arg` is that when I also need to set a name for the optional argument, the entire annotation will become very long, which looks like this:
> > 
> > ```
> > @Arg(value = "target",nullable = true) Player player
> > ```
> > 
> 
> Yeah, you are right. 
> Poll don't clearly show a better solution to do this, but I think your `@NullableArg` seems to be the best way in this situation.
> ![image](https://github.com/Rollczi/LiteCommands/assets/49173834/047d5bad-cc5c-47de-90b1-34a5972641fb)
> 
> So, I will implement `@NullableArg`. Thanks for your help!

Well, after deeplyconsideration, I think use the `@OptionalArg` to name this annotation may be better.

**Comment by Rollczi** [comment]
> 
> Well, after deeplyconsideration, I think use the `@OptionalArg` to name this annotation may be better.

It is also a good solution. This gives me some food for thought...
Hm... what do you think about short alternative `@OptionArg`?

**Comment by rchomczyk** [comment]
From my view the `@OptionalArg` is better name, as the option phrase could be misleading.

**Comment by CarmJos** [comment]
> > 
> > Well, after deeplyconsideration, I think use the `@OptionalArg` to name this annotation may be better.
> 
> It is also a good solution. This gives me some food for thought...
> Hm... what do you think about short alternative `@OptionArg`?

`@OptionArg` is okay, but may cause some misunderstandings. As a result, in my opinion, the `@OptionalArg` is  better, as the same name and behavior with `Optional<>` in arguments.

**Comment by Rollczi** [comment]
You are actually right, `Option` is not smart.

After much discussion and research, I have decided to write arguments for:
#### `optional` keyword
- it better represents the concept of optional arguments.

#### `nullable` keyword
- this indicates that the argument is nullable.

#### `@KeywordArg`
- This annotation is smaller than the use case of `@Arg` with attributes.

#### `@Arg(keyword = true)`
- There are no new annotations. It is more consistent with the rest of the API
- The feature is more closely related to the annotation. (Similarly to the [@RequestParm](https://www.studytonight.com/spring-framework/spring-requestparam-annotation))

**Comment by Rollczi** [comment]
`optional` is great. Also, I don't want to add new annotations to the API to make it more complicated. 
This is a challenging decision because all solutions have pros and cons. I think that's the best solution for the moment, looking at the widely used Spring Boot API.

**Comment by CarmJos** [comment]
> > Another main reason why I personally do not recommend adding new parameters to @Arg is that when I also need to set a > name for the optional argument, the entire annotation will become very long, which looks like this:
> > ```java
> > @Arg(value = "target", nullable = true) Player player
> > ```
> 
> If you add flag `-parameters` [to java compilation](https://github.com/Rollczi/LiteCommands#add--parameters-to-your-compiler-to-use-all-features-of-litecommands) then you can use it to define the name of argument based on the parameter name, which should shorten the code to:
> ```java
> @Arg(optional = true) Player target
> ```
> 

In this example, I use an English arg name. But in reality, the name is often filled in Chinese to prompt the user. Which means I must use this name, instead of filling it in the parameters of the method.

**Comment by Rollczi** [comment]
> > > Another main reason why I personally do not recommend adding new parameters to @Arg is that when I also need to set a > name for the optional argument, the entire annotation will become very long, which looks like this:
> > > ```java
> > > @Arg(value = "target", nullable = true) Player player
> > > ```
> > 
> > If you add flag `-parameters` [to java compilation](https://github.com/Rollczi/LiteCommands#add--parameters-to-your-compiler-to-use-all-features-of-litecommands) then you can use it to define the name of argument based on the parameter name, which should shorten the code to:
> > ```java
> > @Arg(optional = true) Player target
> > ```
> > 
> 
> In this example, I use an English arg name. But in reality, the name is often filled in Chinese to prompt the user. Which means I must use this name, instead of filling it in the parameters of the method.

Unfortunately, in some cases it will be annoying :/

**Comment by CarmJos** [comment]
> > > > Another main reason why I personally do not recommend adding new parameters to @arg is that when I also need to set a > name for the optional argument, the entire annotation will become very long, which looks like this:
> > > > ```java
> > > > @Arg(value = "target", nullable = true) Player player
> > > > ```
> > > 
> > > 
> > > If you add flag `-parameters` [to java compilation](https://github.com/Rollczi/LiteCommands#add--parameters-to-your-compiler-to-use-all-features-of-litecommands) then you can use it to define the name of argument based on the parameter name, which should shorten the code to:
> > > ```java
> > > @Arg(optional = true) Player target
> > > ```
> > 
> > 
> > In this example, I use an English arg name. But in reality, the name is often filled in Chinese to prompt the user. Which means I must use this name, instead of filling it in the parameters of the method.
> 
> Unfortunately, in some cases it will be annoying :/

Yeah, so please think about non-English developers, it will be very disastrous if they can only use `@Arg(value = "目标玩家", nullable = true)` form.

**Comment by huanmeng-qwq** [comment]
https://github.com/Rollczi/LiteCommands/blob/b7ecb1606ee933f973a8ca5d1fb6a354d115d621/litecommands-core/src/dev/rollczi/litecommands/schematic/SchematicGeneratorSimpleImpl.java#L62-L66

I think this part should be abstracted so that developers can customize it, including `argument`

**Comment by Rollczi** [comment]
> Yeah, so please think about non-English developers, it will be very disastrous if they can only use `@Arg(value = "目标玩家", nullable = true)` form.

This is another argument for `@OptionalArg`. I always wait for the feedback in the issue before merge.
I know the discussion is long, but it is very good for development 😁

I was thinking about implementing two ideas at once, but it probably won't be good for the API...

So we're left with `@OptionalArg` if no one has anything to add to the discussion?

**Comment by CarmJos** [comment]
> > Yeah, so please think about non-English developers, it will be very disastrous if they can only use `@Arg(value = "目标玩家", nullable = true)` form.
> 
> This is another argument for `@OptionalArg`. I always wait for the feedback in the issue before merge. I know the discussion is long, but it is very good for development 😁
> 
> I was thinking about implementing two ideas at once, but it probably won't be good for the API...
> 
> So we're left with `@OptionalArg` if no one has anything to add to the discussion?

It seems right, there's only `@OptionalArg` left.
