### ISSUE TITLE
VarArgs Support

### ISSUE THREAD

**Issue by creatorfromhell** [Rollczi/LiteCommands#308]
I think a feature to support VarArgs for commands would be nice. This could be specified by using an array in the argument type.

An example would be with a gamerule command: /world setrules worldname rule1:true rule2:true rule3:true

Code:
```java
public void gamerule(Player sender, @Arg @Name("world") World world, @Arg @Name("gamerule") Gamerule[] rules)
```

Alternative code:
```java
public void gamerule(Player sender, @Arg @Name("world") World world, @VarArg @Name("gamerule") Gamerule[] rules)
```

**Comment by CarmJos** [comment]
I think this feature can be implement by creating a new argument type like `GameruleSetup` with join resolve to process all values.
