### ISSUE TITLE
LiteCommands does not support multiple arguments

### ISSUE THREAD

**Issue by CitralFlo** [Rollczi/LiteCommands#326]
![image](https://github.com/Rollczi/LiteCommands/assets/80779749/6247ae90-51fc-4545-810d-0e0651ad38d2)
As shown above. While using LiteCommands to configure commands, Correct usage shows only first argument, not the second one.

**Comment by Rollczi** [comment]
> ![image](https://private-user-images.githubusercontent.com/80779749/289313250-6247ae90-51fc-4545-810d-0e0651ad38d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjUwOTksIm5iZiI6MTcwMjE2NDc5OSwicGF0aCI6Ii84MDc3OTc0OS8yODkzMTMyNTAtNjI0N2FlOTAtNTFmYy00NTQ1LTgxMGQtMGUwNjUxYWQzOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIzMzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDE0MTllMWQyNDFmYmI1YjgwNDBkOGRkYTcxNGFmMjI2MGYwMDc1YWIwZDQ4NmQzMGEyOTdhODBlN2YwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._16AHhdzdzJhMIjnVERM0IByV2HCifHTD39qkcKGyJY) As shown above. While using LiteCommands to configure commands, Correct usage shows only first argument, not the second one.

Can you send me the code?

**Comment by vLuckyyy** [comment]
> > ![image](https://private-user-images.githubusercontent.com/80779749/289313250-6247ae90-51fc-4545-810d-0e0651ad38d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjUwOTksIm5iZiI6MTcwMjE2NDc5OSwicGF0aCI6Ii84MDc3OTc0OS8yODkzMTMyNTAtNjI0N2FlOTAtNTFmYy00NTQ1LTgxMGQtMGUwNjUxYWQzOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIzMzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDE0MTllMWQyNDFmYmI1YjgwNDBkOGRkYTcxNGFmMjI2MGYwMDc1YWIwZDQ4NmQzMGEyOTdhODBlN2YwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._16AHhdzdzJhMIjnVERM0IByV2HCifHTD39qkcKGyJY) As shown above. While using LiteCommands to configure commands, Correct usage shows only first argument, not the second one.
> 
> Can you send me the code?

all eternalcore commands

**Comment by CitralFlo** [comment]
> > ![image](https://private-user-images.githubusercontent.com/80779749/289313250-6247ae90-51fc-4545-810d-0e0651ad38d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjUwOTksIm5iZiI6MTcwMjE2NDc5OSwicGF0aCI6Ii84MDc3OTc0OS8yODkzMTMyNTAtNjI0N2FlOTAtNTFmYy00NTQ1LTgxMGQtMGUwNjUxYWQzOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIzMzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDE0MTllMWQyNDFmYmI1YjgwNDBkOGRkYTcxNGFmMjI2MGYwMDc1YWIwZDQ4NmQzMGEyOTdhODBlN2YwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._16AHhdzdzJhMIjnVERM0IByV2HCifHTD39qkcKGyJY) As shown above. While using LiteCommands to configure commands, Correct usage shows only first argument, not the second one.
> 
> Can you send me the code?

yes. no problem.

code here: https://github.com/EternalCodeTeam/EternalCore/blob/litecommands-3.0.0/eternalcore-core%2Fsrc%2Fmain%2Fjava%2Fcom%2Feternalcode%2Fcore%2Ffeature%2Fessentials%2Fmob%2FButcherCommand.java
