### ISSUE TITLE
Unsupported return type

### ISSUE THREAD

**Issue by huanmeng-qwq** [Rollczi/LiteCommands#356]
![0d5ce349e45d7a2f70888defd5ef54cb](https://github.com/Rollczi/LiteCommands/assets/49704373/09e7266d-e916-4b8e-8f2e-6534c356aba8)
![edb33d410369b2fe30a4883506d8ef63](https://github.com/Rollczi/LiteCommands/assets/49704373/fcafccb4-a834-4884-8b1c-b022632f970c)

**Comment by CarmJos** [comment]
LiteCommands don't know what do you want to display to players the `int`, so you may need to implement `Int` result by yourself in builder functions, it seems like this:

```java

        LiteCommandsBukkit.builder().result(Integer.class, (invocation, integer, chain) -> {
            invocation.sender().sendMessage("The result is " + integer);
        });

```
