### ISSUE TITLE
MultipleArgumentResolver with 

### ISSUE THREAD

**Issue by MelonHell** [Rollczi/LiteCommands#363]
I have an argument with several parts and I want to make the second part optional

For example, I will make such a logger:
```kt
override fun suggest(
    invocation: Invocation<CommandSender>,
    argument: Argument<String>,
    context: SuggestionContext,
): SuggestionResult {
    println(context.current.multilevelList())
    return SuggestionResult.empty()
}
```
If I specify Range(2, 2), then the suggestions will work correctly, but the second argument will not be optional
```kt
override fun getRange(argument: Argument<String>): Range {
    return Range(2, 2)
}
```
![image](https://github.com/Rollczi/LiteCommands/assets/53826469/22097e7f-79d8-4ffe-98dd-9ec94a7ab491)
![image](https://github.com/Rollczi/LiteCommands/assets/53826469/ee929e31-acac-41c2-99fb-051f28af250a)

If I specify Range(1, 2), then the suggestions will ignore the second argument
```kt
override fun getRange(argument: Argument<String>): Range {
    return Range(1, 2)
}
```
![image](https://github.com/Rollczi/LiteCommands/assets/53826469/356df0cc-50b4-4363-8b71-c973c152f868)
![image](https://github.com/Rollczi/LiteCommands/assets/53826469/ce16e794-97e2-4640-b9f8-8fb7e657e1e5)

**Comment by Rollczi** [comment]
GH-365

**Comment by Rollczi** [comment]
Thanks for your bug report. It will be fixed in the next release. <3
