### ISSUE TITLE
Commandblock Support

### ISSUE THREAD

**Issue by creatorfromhell** [Rollczi/LiteCommands#397]
Not sure if this is a bug or a feature that needs requested, but attempting to use commands created using LiteCommands in command blocks doesn't work.

**Comment by Rollczi** [comment]
Can you show how to recreate a command that doesn't work in a command block? I checked the code and there should be no such problems

**Comment by creatorfromhell** [comment]
> Can you show how to recreate a command that doesn't work in a command block? I checked the code and there should be no such problems

https://github.com/TheNewEconomy/PhantomWorlds/blob/master/src/main/java/me/lokka30/phantomworlds/commands/PWCommand.java

Registration: https://github.com/TheNewEconomy/PhantomWorlds/blob/0a76fe44fc855dc1ad08373722b74770ed4d6bcc/src/main/java/me/lokka30/phantomworlds/PhantomWorlds.java#L253

Go to command block and it doesn't autofill or anything, whereas another plugin on a separate library auto fills and everything.

**Comment by Rollczi** [comment]
I can not reproduce this problem: 
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/38e7975f-6083-475f-85f8-e66ab086c086)
video:
https://cdn.discordapp.com/attachments/896935070823239731/1234627846924668978/20240429-2209-08.3684862.mp4?ex=66316c48&is=66301ac8&hm=1be14a1c9f1a2afe18fe5abf2e6b5b7cd0d62fda8a843d1a896e4293bd053b32&

My server configuration:
server.properties
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/4e315270-ff7a-48eb-8899-4ee8d1fa95d2)


paper-world-defaults.yml
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/e4f4db7a-830a-4d81-b258-d2ebc8ff0ba8)

**Comment by Rollczi** [comment]
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/675a6c0f-9982-4115-80b4-5c9fb41fc1e1)
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/41de55fe-11e1-4506-85c6-01fc68996f57)

**Comment by creatorfromhell** [comment]
> Your plugin also work ![image](https://private-user-images.githubusercontent.com/49173834/326603509-675a6c0f-9982-4115-80b4-5c9fb41fc1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDEzMTAsIm5iZiI6MTcxNDQ0MTAxMCwicGF0aCI6Ii80OTE3MzgzNC8zMjY2MDM1MDktNjc1YTZjMGYtOTk4Mi00MTE1LTgwYjQtNWM5ZmI0MWZjMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMzY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1M2RhZGI0ZjA1ZmNhOTFmODUyMTkyMzg4M2IwZmI1N2NmNmE2MDg1MTc0OGNhNmVlYmEzZGVmMDljZTU3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V7y0LgydZNaWnnw5clDPTOtBUlc2O_t_xm-yXFe-Yus) ![image](https://private-user-images.githubusercontent.com/49173834/326604287-41de55fe-11e1-4506-85c6-01fc68996f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDEzMTAsIm5iZiI6MTcxNDQ0MTAxMCwicGF0aCI6Ii80OTE3MzgzNC8zMjY2MDQyODctNDFkZTU1ZmUtMTFlMS00NTA2LTg1YzYtMDFmYzY4OTk2ZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMzY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OWU2ZDAzOTgzMTcxMTJiZmM4OGZhNDdjNzg0Zjc4Y2Q5ZGVlY2E2YzllNTM2ZWVjNGRkNWFiYWFjODZlNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KrfkbnV_AWGvUP2RcG9GT_DaAEaZLr3qSjwDdRseDvE)

interesting, testing now I'm not able to reproduce again, maybe just some form of weird magic.

Thanks anyways!
