### ISSUE TITLE
Add command/subcommands rate-limit

### ISSUE THREAD

**Issue by bastien-snk** [Rollczi/LiteCommands#398]
Hi,

I think this feature could be a huge plus, especially for servers interacting with external services as a result of a command execution.
Maybe having a parameter for @Command @Execute would be great as it would allow to customize the rate-limit with more control.

**Comment by Rollczi** [comment]
isn't this similar to the `@Cooldown` feature?

**Comment by bastien-snk** [comment]
I did not see this annotation in the docs. But I think this might do the same thing. Do you have a javadoc in addition to the Writerside docs? That might be useful.

**Comment by Rollczi** [comment]
> I did not see this annotation in the docs. But I think this might do the same thing. Do you have a javadoc in addition to the Writerside docs? That might be useful.

javadocs are generated on the fly per modules:
https://repo.panda-lang.org/javadoc/releases/dev/rollczi/litecommands-annotations/3.4.1

**Comment by bastien-snk** [comment]
Okay, thanks. It would be nice to have a direct link directly inside the official documentation
