### ISSUE TITLE
Use a Versioning Catalog (like as `Versions` object)

### ISSUE THREAD

**Issue by KermanIsPretty** [Rollczi/LiteCommands#431]
Lite commands should use a `libs.versions.toml` file to share dependencies, you can find more information under https://docs.gradle.org/current/userguide/platforms.html

This would allow updates to dependencies to not span multiple files but just one and allows you to combine and have one central location for versioning.

**Comment by vLuckyyy** [comment]
We have discussed this a few times with @Rollczi, however, it is not convenient at all..., a better solution is to just make a Versions object in `buildSrc` and put only versions in it, in fact, every time I have to use `libs.versions.toml`, I get lost in it more than if I use the normal version definition

**Comment by Rollczi** [comment]
Yup, an example of this solution: https://github.com/EternalCodeTeam/EternalCore/blob/master/buildSrc/src/main/kotlin/Versions.kt

**Comment by Rollczi** [comment]
Currently, LiteCommands doesn't have `Version` object, so I think we can reopen this issue and add it in the future.

**Comment by vLuckyyy** [comment]
> Currently, LiteCommands doesn't have `Versions` object, so I think we can reopen this issue and add it in the future.

The future is now
