### ISSUE TITLE
 Clean up shchedulers

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#437]
LiteCommands provides a default scheduler [SchedulerExecutorPoolImpl](https://github.com/Rollczi/LiteCommands/blob/0f4af80ffb59d0c5b55b9f431f2971c63a30d187/litecommands-core/src/dev/rollczi/litecommands/scheduler/SchedulerExecutorPoolImpl.java) but it may not be the best way to control threads on platforms such as Fabric BungeeCord Fabric Sponge Velocity

**Comment by BlackBaroness** [comment]
@Rollczi I will take that, i think i will finish it in 5-10 days
