### ISSUE TITLE
JDA String Command Argument errors

### ISSUE THREAD

**Issue by Knerio** [Rollczi/LiteCommands#469]
Im currently trying to update the framework from a very old version, but somehow string arguments arent working properly.
Version 3.5.0 command input:
![image](https://github.com/user-attachments/assets/826b1eea-fbd7-465f-bcb4-8115e00dc97b)
In my console this apears too:
![image](https://github.com/user-attachments/assets/b2fdb0d4-8b2c-4179-a5a1-2bfeaa3a79e4)
But if i upgrade to version 3.6.0:
![image](https://github.com/user-attachments/assets/8a194820-5d2a-489a-bbf8-a33099fb7f3e)
But in my console i only reveice this:
![image](https://github.com/user-attachments/assets/76ac9a35-0fff-4ca9-a2fb-a2ac4e6c4739)

My Factory isnt really configured, thats why i dont see why this problem occurs:
```java
  LiteJDAFactory.builder(jda)
                .commands(commands)     
                .exceptionUnexpected((invocation, throwable, resultHandlerChain) -> {
                    Module.logThrowable(this, throwable);
                })
                .annotations(configuration -> {
                    configuration.methodValidator(context -> {
                       ...
                    });
                })
                .build();
```

I appreciate any help

**Comment by Rollczi** [comment]
Can you show me your commands files?

**Comment by Knerio** [comment]
> Can you show me your commands files?

I just added you to the repository (https://github.com/Knerio/VaxBot)
And what exactly do you mean by commands files?

**Comment by Rollczi** [comment]
Can you replace `@Arg` to `@Join` in this command? I think this can help in this case

**Comment by Knerio** [comment]
> Can you replace `@Arg` to `@Join` in this command? I think this can help in this case

That works, but thats not really the point of @Join, right?

**Comment by Knerio** [comment]
And @Join also works for integers, should i just replace every @Arg with @Join?

**Comment by Rollczi** [comment]
> > Can you replace `@Arg` to `@Join` in this command? I think this can help in this case
> 
> That works, but thats not really the point of @Join, right?

This is poit of it

**Comment by Rollczi** [comment]
> And @Join also works for integers, should i just replace every @arg with @Join?

Nope, you can not parse "24 56 43" to int

**Comment by Rollczi** [comment]
Fixed https://github.com/Rollczi/LiteCommands/pull/476
