### ISSUE TITLE
[Fabric] Class file for net.minecraft.class_2168 not found

### ISSUE THREAD

**Issue by RedCarl** [Rollczi/LiteCommands#489]
15:21:57: 正在执行 'build'…

> Configure project :OociCore
Fabric Loom: 1.8.12

> Task :OociCore:compileJava FAILED
1 actionable task: 1 executed
/Users/redcarl/IdeaProjects/ooci-fabric/OociCore/src/main/java/co/ooci/fabric/core/OociCore.java:20: 错误: 无法访问class_2168
        LiteFabricFactory.server().commands(command).build();
                         ^
  找不到net.minecraft.class_2168的类文件
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':OociCore:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 834ms
15:21:58: 执行完成 'build'。

**Comment by huanmeng-qwq** [comment]
Please provide the minecraft version, fabric version and related gradle build script files

**Comment by RedCarl** [comment]
> 请提供 minecraft 版本、fabric 版本和相关 gradle 构建脚本文件

	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	loader_version=0.16.9
	fabric_version=0.110.0+1.21.1
        构建: ./gradle build

**Comment by RedCarl** [comment]
https://paste.fastmirror.net/?69d43764def8954e#8BrPxYMLL8vkXV4CYQd5dBNvWr5kHomo1govbdYyBvVj

**Comment by huanmeng-qwq** [comment]
The following paragraph is correct:
```kts
modImplementation("dev.rollczi:litecommands-fabric:${project.litecommands_version}")
// include modImplementation("dev.rollczi:litecommands-fabric:${project.litecommands_version}") < It will be included when build
```

related link: https://wiki.fabricmc.net/zh_cn:documentation:fabric_loom

**Comment by RedCarl** [comment]
Thank you very much, problem solved!
```
include modImplementation("dev.rollczi:litecommands-fabric:${project.litecommands_version}")
```
