### ISSUE TITLE
JDA registration speed on the jda vs on a guild

### ISSUE THREAD

**Issue by Koboo** [Rollczi/LiteCommands#507]
Hey there,
I dived into the source of litecommands-jda and checked the implementation of the command registration. 
I'm having the issue that my commands take very long to update/upsert if I'm using litecommands instead of using jda directly. 
After I checked the way litecommands registers the commands on the JDA instance using the upsertCommands(..) method, I checked the jda implementation and noticed, that there's a big difference if you call jda.upsertCommands(..) vs guild.upsertCommands(..). Looking at the source and documentation of jda itself, these are two completley different endpoints of the discord api. That means discord is updating the guild commands much faster than the registration on the JDA instance. 

Now my question is: Could there be a method to update Commands specifically on a guild or a guild list, instead of just using the JDA instance itself, so we can speed up command registration?

I'm talking about the registration speed of several hours vs. instantly. 🙂

The mentioned endpoint difference:
For the bot itself it uses these two
https://github.com/discord-jda/JDA/blob/master/src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java#L50
https://github.com/discord-jda/JDA/blob/master/src/main/java/net/dv8tion/jda/api/requests/Route.java#L64

and these two get called for the guild
https://github.com/discord-jda/JDA/blob/master/src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java#L57
https://github.com/discord-jda/JDA/blob/master/src/main/java/net/dv8tion/jda/api/requests/Route.java#L71

(I already wrote in the discord server and just created a issue for the case.)

**Comment by Rollczi** [comment]
Thanks for your report, I intend to make changes to this issue
